export const products = [
  {
    slug: "chef-pull-out-kitchen-mixer",
    verticalSlug: "kitchen",
    categorySlug: "kitchen-faucets-sinks",
    name: "Chef Pull-Out Kitchen Mixer",
    collection: "Chef Collection",
    shortDescription: "A pull-out mixer with dual spray modes for prep and clean-up.",
    finishes: ["Chrome", "Brushed Steel", "Matte Black"],
    tags: ["Bestseller"],
    featured: true,
    isNew: false,
    sortOrder: 10,
  },
  {
    slug: "atelier-undermount-kitchen-sink",
    verticalSlug: "kitchen",
    categorySlug: "kitchen-faucets-sinks",
    name: "Atelier Undermount Kitchen Sink",
    collection: "Atelier Collection",
    shortDescription: "A deep stainless steel bowl with a quiet, seamless install.",
    finishes: ["Brushed Steel", "Gunmetal"],
    tags: ["New"],
    featured: false,
    isNew: true,
    sortOrder: 20,
  },
  {
    slug: "prepstation-workstation-sink-set",
    verticalSlug: "kitchen",
    categorySlug: "kitchen-faucets-sinks",
    name: "PrepStation Workstation Sink Set",
    collection: "PrepStation Collection",
    shortDescription: "An integrated sink kit with accessories for compact prep zones.",
    finishes: ["Brushed Steel", "Matte Black"],
    tags: [],
    featured: false,
    isNew: false,
    sortOrder: 30,
  },
  {
    slug: "marquina-porcelain-countertop-slab",
    verticalSlug: "kitchen",
    categorySlug: "kitchen-surfaces-backsplashes",
    name: "Marquina Porcelain Countertop Slab",
    collection: "Kitchen Slab Edit",
    shortDescription: "A dramatic stone-look slab for counters and islands.",
    finishes: ["Polished", "Honed"],
    tags: ["Bestseller"],
    featured: true,
    isNew: false,
    sortOrder: 40,
  },
  {
    slug: "metro-glossy-backsplash-tile",
    verticalSlug: "kitchen",
    categorySlug: "kitchen-surfaces-backsplashes",
    name: "Metro Glossy Backsplash Tile",
    collection: "Metro Edit",
    shortDescription: "A crisp glossy tile for bright, easy-clean backsplashes.",
    finishes: ["Glossy"],
    tags: [],
    featured: false,
    isNew: false,
    sortOrder: 50,
  },
  {
    slug: "terra-matte-stone-backsplash",
    verticalSlug: "kitchen",
    categorySlug: "kitchen-surfaces-backsplashes",
    name: "Terra Matte Stone Backsplash",
    collection: "Terra Edit",
    shortDescription: "Warm stone texture for calm kitchen walls.",
    finishes: ["Matte", "Textured"],
    tags: ["New"],
    featured: false,
    isNew: true,
    sortOrder: 60,
  },
  {
    slug: "axis-soft-close-drawer-system",
    verticalSlug: "kitchen",
    categorySlug: "kitchen-storage-hardware",
    name: "Axis Soft-Close Drawer System",
    collection: "Axis Collection",
    shortDescription: "A full-extension drawer system for modular kitchens.",
    finishes: ["Graphite", "Stainless Steel"],
    tags: ["Bestseller"],
    featured: true,
    isNew: false,
    sortOrder: 70,
  },
  {
    slug: "larder-tall-pantry-pull-out",
    verticalSlug: "kitchen",
    categorySlug: "kitchen-storage-hardware",
    name: "Larder Tall Pantry Pull-Out",
    collection: "Larder Collection",
    shortDescription: "Tall pantry storage with smooth access from both sides.",
    finishes: ["Graphite", "Stainless Steel"],
    tags: [],
    featured: false,
    isNew: false,
    sortOrder: 80,
  },
  {
    slug: "cornerflow-carousel-basket",
    verticalSlug: "kitchen",
    categorySlug: "kitchen-storage-hardware",
    name: "CornerFlow Carousel Basket",
    collection: "CornerFlow Collection",
    shortDescription: "A rotating corner unit that makes deep cabinets usable.",
    finishes: ["Stainless Steel", "Graphite"],
    tags: ["New"],
    featured: false,
    isNew: true,
    sortOrder: 90,
  },
];
