import { Product } from "./types";

export const products: Product[] = [
  // ---------- Towel Racks & Holders ----------
  {
    slug: "aluminum-folding-towel-rack-black-24in",
    vertical: "bathroom-accessories",
    categorySlug: "towel-racks",
    name: "Aluminum Folding Towel Rack with Hooks - Black, 24 Inch",
    collection: "Towel Rack",
    shortDescription: "A foldable black aluminum towel rack with a shelf, rod, and five hooks.",
    description:
      "A foldable towel rack machined from high-strength aluminum and finished with a seven-layer powder coating for rust resistance and durability. The unit combines a top shelf for folded towels, a hanging rod for bath towels, and five utility hooks in a single wall-mounted fixture. It folds flat against the wall when not in use, making it suitable for compact bathrooms, and installs with the included wall-mounting hardware.",
    finishes: ["Black"],
    sizes: ["24 inch"],
    specs: [
      { label: "Material", value: "Aluminum (powder coated)" },
      { label: "Finish/Color", value: "Black, matte powder coated" },
      { label: "Dimensions", value: "59 x 25.5 x 14 cm" },
      { label: "Weight", value: "1.28 kg" },
      { label: "Installation", value: "Wall-mounted" },
    ],
    tags: [],
    tone: "bath",
  },
  {
    slug: "stainless-steel-towel-rack-chrome-24in",
    vertical: "bathroom-accessories",
    categorySlug: "towel-racks",
    name: "304 Grade Stainless Steel Towel Rack - Chrome, 24 Inch",
    collection: "Towel Rack",
    shortDescription: "A 304-grade stainless steel folding rack with a swivel bar and four hooks.",
    description:
      "A folding towel rack built from 304-grade stainless steel with a nickel-chrome mirror finish that resists rust, scratches, and fingerprints. The design pairs a swivel towel bar with a small shelf and four fixed hooks for additional bathroom items. It mounts to the wall with the included hardware and wipes clean with a soft cloth.",
    finishes: ["Chrome"],
    sizes: ["24 inch"],
    specs: [
      { label: "Material", value: "304-grade stainless steel" },
      { label: "Finish/Color", value: "Chrome, nickel-chrome mirror finish" },
      { label: "Dimensions", value: "61 x 24 x 17.5 cm" },
      { label: "Weight", value: "1.49 kg" },
      { label: "Installation", value: "Wall-mounted" },
    ],
    tags: [],
    tone: "bath",
  },
  {
    slug: "stainless-steel-towel-bar-black-24in",
    vertical: "bathroom-accessories",
    categorySlug: "towel-racks",
    name: "Stainless Steel Towel Rack with Foldable Rod - Black, 24 Inch",
    collection: "Towel Rack",
    shortDescription: "A black stainless steel towel rack with a foldable shelf and rod.",
    description:
      "A stainless steel towel rack with a 24-inch frame finished in black powder coating for a rust-resistant, fingerprint-resistant surface. The upper shelf and lower rod both fold flat to save space when the rack is not holding towels. It mounts to the wall using the included screws and hardware and cleans with a soft cloth.",
    finishes: ["Black"],
    sizes: ["24 inch"],
    specs: [
      { label: "Material", value: "Stainless steel" },
      { label: "Finish/Color", value: "Black, powder coated" },
      { label: "Dimensions", value: "59.5 x 21.5 x 21.5 cm" },
      { label: "Weight", value: "1.26 kg" },
      { label: "Installation", value: "Wall-mounted" },
    ],
    tags: [],
    tone: "bath",
  },
  {
    slug: "folding-towel-rack-chrome-8-hooks-24in",
    vertical: "bathroom-accessories",
    categorySlug: "towel-racks",
    name: "Stainless Steel Folding Towel Rack with Swivel Bar - Chrome, 24 Inch",
    collection: "Towel Rack",
    shortDescription: "A chrome-finished folding towel rack with a swivel bar and eight hooks.",
    description:
      "A stainless steel towel rack finished in a nickel-chrome mirror coat that resists rust, water, and corrosion while keeping a bright, reflective surface. It combines a swivel towel bar with four double cross hooks, giving eight hanging points for towels, robes, and washcloths. The 24-inch unit folds for space efficiency and mounts to the wall with the supplied screws.",
    finishes: ["Chrome"],
    sizes: ["24 inch"],
    specs: [
      { label: "Material", value: "Stainless steel" },
      { label: "Finish/Color", value: "Chrome, nickel-chrome mirror finish" },
      { label: "Dimensions", value: "63 x 24 x 12 cm" },
      { label: "Weight", value: "1.52 kg" },
      { label: "Hooks", value: "4 double cross hooks (8 hanging points)" },
      { label: "Installation", value: "Wall-mounted" },
    ],
    tags: [],
    tone: "bath",
  },
  {
    slug: "aluminium-swivel-towel-hanger-black-24in",
    vertical: "bathroom-accessories",
    categorySlug: "towel-racks",
    name: "Aluminium Folding Towel Hanger with 90 Degree Swivel Rod - Black, 24 Inch",
    collection: "Towel Rack",
    shortDescription: "A black aluminum towel hanger with a swivel rod and seven hooks.",
    description:
      "A folding towel hanger made from powder-coated aluminum that resists rust and daily wear. It combines a 90-degree swivel rod for hanging bath towels, seven fixed hooks for robes and smaller items, and a top shelf for bath products, all in a single 24-inch wall-mounted fixture. The rack folds away when not in use and is cleaned by wiping with a soft cotton cloth.",
    finishes: ["Black"],
    sizes: ["24 inch"],
    specs: [
      { label: "Material", value: "Aluminium, powder coated" },
      { label: "Finish/Color", value: "Black" },
      { label: "Dimensions", value: "59 x 23.5 x 14 cm" },
      { label: "Weight", value: "0.86 kg" },
      { label: "Hooks", value: "7 fixed hooks" },
      { label: "Installation", value: "Wall-mounted" },
    ],
    tags: [],
    tone: "bath",
  },
  {
    slug: "eco-stainless-steel-towel-rack-chrome-24in",
    vertical: "bathroom-accessories",
    categorySlug: "towel-racks",
    name: "Eco Stainless Steel Folding Towel Rack - Chrome, 24 Inch",
    collection: "Towel Rack",
    shortDescription: "A compact chrome stainless steel folding rack with four movable hooks.",
    description:
      "A stainless steel towel rack with a nickel-chrome mirror finish that resists rust, scratches, and fingerprints. The 24-inch fixture folds flat and includes a top shelf for bath products along with four movable hooks for towels and robes. It mounts to the wall with the included screws and wipes clean with a soft cloth.",
    finishes: ["Chrome"],
    sizes: ["24 inch"],
    specs: [
      { label: "Material", value: "Stainless steel" },
      { label: "Finish/Color", value: "Chrome, nickel-chrome mirror finish" },
      { label: "Dimensions", value: "58 x 25.5 x 9.5 cm" },
      { label: "Weight", value: "1 kg" },
      { label: "Hooks", value: "4 movable hooks" },
      { label: "Installation", value: "Wall-mounted" },
    ],
    tags: [],
    tone: "bath",
  },
  {
    slug: "stillness-double-hotelier-rose-gold-24in",
    vertical: "bathroom-accessories",
    categorySlug: "towel-racks",
    name: 'Stillness 24" (610mm) Double Hotelier',
    collection: "Towel Rack",
    shortDescription: "A solid brass double towel bar in Kohler's minimalist Stillness line.",
    description:
      "The Stillness collection double hotelier is a 24-inch (610mm) towel bar machined from solid brass and finished in Kohler's vibrant rose gold plating, which the brand states exceeds industry corrosion and tarnish-resistance standards. Its simplified, minimalist form is designed to coordinate with a range of contemporary bathroom styles. The bar mounts horizontally using Kohler's easy-installation system, which does not require drilling and allows the fixture to be removed without leaving marks.",
    finishes: ["Rose Gold"],
    sizes: ["24 inch"],
    specs: [
      { label: "Material", value: "Solid brass" },
      { label: "Finish/Color", value: "Vibrant Rose Gold" },
      { label: "Length", value: "24 inch (610mm)" },
      { label: "Installation", value: "Horizontal wall mount, no drilling required" },
      { label: "Collection", value: "Stillness" },
    ],
    tags: [],
    tone: "bath",
  },
  {
    slug: "304-ss-dual-folding-towel-hanger-chrome-24in",
    vertical: "bathroom-accessories",
    categorySlug: "towel-racks",
    name: "304 Grade Stainless Steel Dual Folding Towel Hanger - Chrome, 24 Inch",
    collection: "Towel Rack",
    shortDescription: "A 304 stainless steel dual towel hanger with six hooks total.",
    description:
      "A dual folding towel hanger built from 304-grade stainless steel, chosen for its resistance to rust, corrosion, and daily wear in humid bathroom conditions. It combines a spacious top rack for towels with a lower bar, plus four movable hooks and two double bottom hooks for additional hanging capacity. The top shelf folds down to save space, and the unit installs with the included mounting hardware.",
    finishes: ["Chrome"],
    sizes: ["24 inch"],
    specs: [
      { label: "Material", value: "304-grade stainless steel" },
      { label: "Finish/Color", value: "Chrome, nickel-chrome mirror finish" },
      { label: "Dimensions", value: "59.5 x 24 x 21 cm" },
      { label: "Weight", value: "2.1 kg" },
      { label: "Hooks", value: "4 movable hooks + 2 double bottom hooks" },
      { label: "Installation", value: "Wall-mounted" },
    ],
    tags: [],
    tone: "bath",
  },
  {
    slug: "heavy-duty-dual-towel-rack-chrome-pack-of-2",
    vertical: "bathroom-accessories",
    categorySlug: "towel-racks",
    name: "Heavy-Duty Stainless Steel Dual Folding Towel Rack - Chrome, 24 Inch (Pack of 2)",
    collection: "Towel Rack",
    shortDescription: "A chrome stainless steel dual folding towel rack, sold as a pack of two.",
    description:
      "A heavy-duty stainless steel towel rack finished with a nickel-chrome mirror coat that resists daily wear and fingerprints. Each 24-inch unit has a foldable upper shelf for larger bath products and a foldable lower rod that tucks away when not needed, and the set ships as a pack of two. Installation hardware is included, and the rack cleans with a soft cloth.",
    finishes: ["Chrome"],
    sizes: ["24 inch"],
    specs: [
      { label: "Material", value: "Stainless steel" },
      { label: "Finish/Color", value: "Chrome, nickel-chrome mirror finish" },
      { label: "Dimensions", value: "60 x 22.5 x 21.5 cm" },
      { label: "Weight", value: "3.02 kg (pack of 2)" },
      { label: "Pack Size", value: "2 units" },
      { label: "Installation", value: "Wall-mounted" },
    ],
    tags: [],
    tone: "bath",
  },
  {
    slug: "towel-rack-hooks-chrome-pack-of-1",
    vertical: "bathroom-accessories",
    categorySlug: "towel-racks",
    name: "24 Inch Towel Rack with Hooks - Chrome, Pack of 1",
    collection: "Towel Rack",
    shortDescription: "A chrome towel rack with an integrated bar and seven hooks.",
    description:
      "A 24-inch stainless steel towel rack finished in a nickel-chrome mirror coat for corrosion resistance. It combines an integrated towel bar with four fixed hooks and three swivel hooks, giving several ways to hang towels, robes, and clothing. The unit is wall-mounted with the included hardware and designed for bathrooms with limited space.",
    finishes: ["Chrome"],
    sizes: ["24 inch"],
    specs: [
      { label: "Material", value: "Stainless steel" },
      { label: "Finish/Color", value: "Chrome, nickel-chrome mirror finish" },
      { label: "Dimensions", value: "60 x 24 x 21.5 cm" },
      { label: "Weight", value: "1.75 kg" },
      { label: "Hooks", value: "4 fixed hooks + 3 swivel hooks" },
      { label: "Installation", value: "Wall-mounted" },
    ],
    tags: [],
    tone: "bath",
  },

  // ---------- Commodes: Wall-Mounted ----------
  {
    slug: "platinum-rimless-wall-mounted-commode-white",
    vertical: "bathroom-accessories",
    categorySlug: "sanitaryware",
    name: "Platinum Ceramic Rimless Wall Mounted Commode/P Trap Washdown Flush Commode with Soft Close Toilet Seat Cover (White)",
    collection: "Wall-Mounted Commode",
    shortDescription: "Rimless washdown wall-mounted commode with soft-close seat in white.",
    description:
      "A wall-mounted ceramic commode with a rimless washdown flush for efficient cleaning, paired with a P-trap outlet and a soft-close toilet seat cover in a white matt finish. The wall-hung design conceals the tank for a streamlined look and leaves a gap between the floor and the bowl for easier cleaning underneath. The fully glazed ceramic body is fired at high temperature for durability and stain resistance.",
    finishes: ["White"],
    sizes: ["48 x 36 x 35 cm"],
    specs: [
      { label: "Material", value: "Ceramic" },
      { label: "Flush Type", value: "Rimless Washdown" },
      { label: "Trap Type", value: "P-Trap" },
      { label: "Seat Type", value: "Soft-close" },
      { label: "Installation", value: "Wall-mounted" },
      { label: "Dimensions", value: "48 x 36 x 35 cm" },
    ],
    tags: [],
    tone: "bath",
  },
  {
    slug: "platinum-wall-hung-commode-palm",
    vertical: "bathroom-accessories",
    categorySlug: "sanitaryware",
    name: "Platinum Ceramic Wall Hung Commode/P Trap Western Commode for Toilet/Rim Washdown Western Toilet with Soft Close Toilet Seat Cover (Palm)",
    collection: "Wall-Mounted Commode",
    shortDescription: "Wall-hung rim washdown commode with soft-close seat in palm.",
    description:
      "A wall-hung ceramic commode with a rim washdown flush and P-trap outlet, finished in a palm color tone and fitted with a soft-close toilet seat cover. The space-saving wall-mounted design keeps the floor area clear, and the fully glazed bowl is built to stay clean and reduce cleaning frequency. Wall mounting also creates a gap between the floor and the commode that helps limit bacteria buildup.",
    finishes: ["Palm"],
    sizes: ["51 x 35 x 36.5 cm"],
    specs: [
      { label: "Material", value: "Ceramic" },
      { label: "Flush Type", value: "Rim Washdown" },
      { label: "Trap Type", value: "P-Trap" },
      { label: "Seat Type", value: "Soft-close" },
      { label: "Installation", value: "Wall-mounted" },
      { label: "Dimensions", value: "51 x 35 x 36.5 cm" },
    ],
    tags: [],
    tone: "bath",
  },
  {
    slug: "rimless-wall-hung-commode-brown",
    vertical: "bathroom-accessories",
    categorySlug: "sanitaryware",
    name: "Western Commode/Ceramic Wall Hung Commode for Toilet/Rimless Washdown Western Toilet with Soft Close Toilet Seat - P Trap - (LAS05, Brown)",
    collection: "Wall-Mounted Commode",
    shortDescription: "Rimless washdown wall-hung commode with soft-close seat in matt brown.",
    description:
      "A wall-mounted ceramic commode with a rimless washdown flush and P-trap outlet, finished in a matt brown tone and fitted with a soft-close toilet seat. The high-temperature fired ceramic body is designed to resist stains and scratches, and the concealed tank gives the fixture a clean, modern look. The wall-hung installation removes the floor footprint, and the resulting gap helps limit bacterial buildup.",
    finishes: ["Brown"],
    sizes: ["51.5 x 36.5 x 37.5 cm"],
    specs: [
      { label: "Material", value: "Ceramic (matt finish)" },
      { label: "Flush Type", value: "Rimless Washdown" },
      { label: "Trap Type", value: "P-Trap" },
      { label: "Seat Type", value: "Soft-close" },
      { label: "Installation", value: "Wall-mounted" },
      { label: "Dimensions", value: "51.5 x 36.5 x 37.5 cm" },
    ],
    tags: [],
    tone: "bath",
  },
  {
    slug: "imported-wall-hung-commode-black",
    vertical: "bathroom-accessories",
    categorySlug: "sanitaryware",
    name: "Imported Ceramic Wall Hung Commode/Rimless Washdown Western Toilet/P Trap Western Commode with Soft Close Toilet Seat (Matt Black)",
    collection: "Wall-Mounted Commode",
    shortDescription: "Imported rimless washdown wall-hung commode with soft-close seat in matt black.",
    description:
      "An imported ceramic wall-hung commode with a rimless washdown flush that uses pressure jets around the bowl to clean every surface, paired with a P-trap outlet and a soft-close toilet seat in a matt black finish. The high-temperature fired ceramic is built for durability and stain resistance, with a concealed tank for a modern, streamlined appearance. Its compact, space-saving footprint suits smaller bathrooms.",
    finishes: ["Matt Black"],
    sizes: ["36.5 x 50 x 35 cm"],
    specs: [
      { label: "Material", value: "Ceramic" },
      { label: "Flush Type", value: "Rimless Washdown" },
      { label: "Trap Type", value: "P-Trap" },
      { label: "Seat Type", value: "Soft-close" },
      { label: "Installation", value: "Wall-mounted" },
      { label: "Dimensions", value: "36.5 x 50 x 35 cm" },
    ],
    tags: [],
    tone: "bath",
  },
  {
    slug: "imported-rimless-commode-grey-glossy",
    vertical: "bathroom-accessories",
    categorySlug: "sanitaryware",
    name: "Imported Ceramic Rimless Commode for Toilet/Wall Hung Western Toilet/Washdown Commode with Soft Closing Toilet Seat Cover - P Trap Outlet (1183, Grey Glossy)",
    collection: "Wall-Mounted Commode",
    shortDescription: "Rimless washdown wall-hung commode with soft-close seat in glossy grey.",
    description:
      "An imported wall-hung ceramic commode with a rimless washdown flush that uses water jets around the bowl's rim for thorough cleaning, fitted with a P-trap outlet and a soft-closing toilet seat cover in a glossy grey finish. The ceramic body is fired at high temperature for durability and stain resistance, with a fully glazed surface and concealed tank for a modern look. Its space-saving size suits apartments and smaller bathrooms.",
    finishes: ["Grey Glossy"],
    sizes: ["57 x 42 x 39 cm"],
    specs: [
      { label: "Material", value: "Ceramic" },
      { label: "Flush Type", value: "Rimless Washdown" },
      { label: "Trap Type", value: "P-Trap Outlet" },
      { label: "Seat Type", value: "Soft-close" },
      { label: "Installation", value: "Wall-mounted" },
      { label: "Dimensions", value: "57 x 42 x 39 cm" },
    ],
    tags: [],
    tone: "bath",
  },

  // ---------- Commodes: One-Piece Western ----------
  {
    slug: "one-piece-siphonic-commode-white",
    vertical: "bathroom-accessories",
    categorySlug: "sanitaryware",
    name: "Ceramic Commode For Toilet/One Piece Western Commode With Rimless Siphonic Flush/Commode With Soft Closing Toilet Seat - S Trap - (Hexa, White)",
    collection: "One-Piece Western Commode",
    shortDescription: "One-piece dual-flush siphonic commode with soft-close seat in glossy white.",
    description:
      "A one-piece ceramic western commode with a rimless siphonic dual flush, offering an 8-litre deep flush for solid waste and a 4-litre gentle flush for liquid waste, set on an S-trap outlet positioned 225mm from the wall. The soft-close toilet seat uses hinges designed to prevent slamming and reduce noise, and the glossy white ceramic surface is fully glazed for easy cleaning. It is backed by a 7-year warranty against manufacturing defects, including 2 years of free service on the flush mechanism.",
    finishes: ["White"],
    sizes: ["37 x 65 x 74.5 cm"],
    specs: [
      { label: "Material", value: "Ceramic" },
      { label: "Flush Type", value: "Rimless Siphonic Dual Flush (4L/8L)" },
      { label: "Trap Type", value: "S-Trap" },
      { label: "Seat Type", value: "Soft-close" },
      { label: "Warranty", value: "7 years (2 years free mechanism service)" },
      { label: "Dimensions", value: "37 x 65 x 74.5 cm" },
    ],
    tags: [],
    tone: "bath",
  },
  {
    slug: "vacuum-jet-flush-commode-black",
    vertical: "bathroom-accessories",
    categorySlug: "sanitaryware",
    name: "Ceramic Toilet for Commode/Siphonic Vacuum Jet Flush Ceramic Western Commode/One Piece Western Toilet with Soft Closing Toilet Seat - S Trap (Black)",
    collection: "One-Piece Western Commode",
    shortDescription: "One-piece siphonic vacuum-jet flush commode with soft-close seat in glossy black.",
    description:
      "A one-piece ceramic western toilet with a siphonic vacuum jet flush designed for a strong, clog-free flush that stays quiet and leak-proof, set on an S-trap outlet 230mm from the wall. It includes a soft-close toilet seat with a silent slow-down cover board and an anti-vibration foot pad, finished in a glossy black. The ceramic body is built for strength and durability with a sleek, modern profile.",
    finishes: ["Black"],
    sizes: ["41 x 75 x 70 cm"],
    specs: [
      { label: "Material", value: "Ceramic" },
      { label: "Flush Type", value: "Siphonic Vacuum Jet" },
      { label: "Trap Type", value: "S-Trap" },
      { label: "Seat Type", value: "Soft-close" },
      { label: "Installation", value: "Floor-mounted" },
      { label: "Dimensions", value: "41 x 75 x 70 cm" },
    ],
    tags: [],
    tone: "bath",
  },
  {
    slug: "imported-2d-siphonic-commode-white-grey",
    vertical: "bathroom-accessories",
    categorySlug: "sanitaryware",
    name: "Imported Ceramic Commode/Rimless 2D Siphonic Flush Western Toilet/Bathroom Commode with Soft Closing Toilet Seat Cover - S Trap (White & Grey)",
    collection: "One-Piece Western Commode",
    shortDescription: "Imported rimless 2D siphonic-flush commode with soft-close seat in white and grey.",
    description:
      "An imported one-piece ceramic commode with a rimless 2D siphonic flush using 6 litres of water, set on an S-trap outlet positioned 300mm from the wall. The soft-closing toilet seat cover has a silent slow-down mechanism, and the ceramic body is fired at high temperature to resist stains and scratches, finished in white and grey. An anti-vibration foot pad reduces friction for quieter, more stable use.",
    finishes: ["White", "Grey"],
    sizes: ["50.5 x 67 x 63 cm"],
    specs: [
      { label: "Material", value: "Ceramic" },
      { label: "Flush Type", value: "Rimless 2D Siphonic (6L)" },
      { label: "Trap Type", value: "S-Trap" },
      { label: "Seat Type", value: "Soft-close" },
      { label: "Installation", value: "Floor-mounted" },
      { label: "Dimensions", value: "50.5 x 67 x 63 cm" },
    ],
    tags: [],
    tone: "bath",
  },
  {
    slug: "imported-vacuum-jet-commode-glossy-grey",
    vertical: "bathroom-accessories",
    categorySlug: "sanitaryware",
    name: "Imported Ceramic Western Toilet/Rimless Commode for Toilet/Siphonic Vacuum Jet Flush One Piece Commode With Soft Close Toilet Seat - S Trap Outlet (Glossy Grey)",
    collection: "One-Piece Western Commode",
    shortDescription: "One-piece rimless siphonic vacuum-jet commode with soft-close seat in glossy grey.",
    description:
      "An imported one-piece ceramic western commode with a rimless design and a single-button siphonic vacuum jet flush, delivering a powerful flush with minimal noise through an S-trap outlet. It comes with an inbuilt soft-close toilet seat and a smooth, seamless ceramic surface finished in glossy grey. The high-quality ceramic body is built for durability, a smooth finish, and resistance to stains.",
    finishes: ["Glossy Grey"],
    sizes: [],
    specs: [
      { label: "Material", value: "Ceramic" },
      { label: "Flush Type", value: "Siphonic Vacuum Jet" },
      { label: "Trap Type", value: "S-Trap Outlet" },
      { label: "Seat Type", value: "Soft-close (inbuilt)" },
      { label: "Installation", value: "Floor-mounted" },
    ],
    tags: [],
    tone: "bath",
  },

  // ---------- Commodes: Pan Indian Toilet ----------
  {
    slug: "orissa-pan-indian-toilet-white",
    vertical: "bathroom-accessories",
    categorySlug: "sanitaryware",
    name: "Orrisa Pan Indian Toilet for Bathroom/Household Squating Pan/Sintered Base Ceramic Sanitaryware Commode - (WC-01, White)",
    collection: "Indian Pan Toilet",
    shortDescription: "Sintered-base ceramic squatting pan with rust-free glazing in white.",
    description:
      "A ceramic Indian-style squatting pan with a sintered base and rust-free glazing, shaped with a symmetrical, gently curved form for comfortable use by people of all ages. The smooth, continuously glazed surface includes non-glazed sections intended to make cleaning easier and improve hygiene. Finished in white, it is suited to both domestic and commercial washrooms.",
    finishes: ["White"],
    sizes: ["60.5 x 45.5 x 15.5 cm"],
    specs: [
      { label: "Material", value: "Ceramic (sintered base)" },
      { label: "Glazing", value: "Rust-free glazing" },
      { label: "Type", value: "Squatting Pan" },
      { label: "Color", value: "White" },
      { label: "Dimensions", value: "60.5 x 45.5 x 15.5 cm" },
    ],
    tags: [],
    tone: "bath",
  },

  // ---------- Shower Panels ----------
  {
    slug: "deluxe-circular-shower-panel-black",
    vertical: "bathroom-accessories",
    categorySlug: "showers",
    name: "Deluxe Circular Shower Panel Set with Overhead Shower and Hand Shower",
    collection: "Shower Panel",
    shortDescription: "Wall-mounted circular shower panel with overhead and hand shower plus a hot and cold mixer.",
    description:
      "A wall-mounted shower panel combining an adjustable-angle circular overhead shower with a separate hand shower, built from a combination of brass, stainless steel and ABS components. A hot and cold mixer faucet with dual outlet control lets the user switch between the overhead and hand shower, and a temperature lock feature helps guard against scalding. The set includes the shower head and fitting rod, the hand shower, the mixer faucet, and the fitting material needed for wall installation.",
    finishes: ["Black"],
    sizes: [],
    specs: [
      { label: "Material", value: "Brass, Stainless Steel and ABS" },
      { label: "Valve Type", value: "Hot and cold mixer with temperature control" },
      { label: "Installation", value: "Wall mount" },
      { label: "Functions", value: "Circular overhead shower with adjustable angle, hand shower, dual outlet switching knobs" },
      { label: "Recommended Water Pressure", value: "2-3 bar" },
      { label: "Weight", value: "4.3 kg" },
    ],
    tags: [],
    tone: "bath",
  },
  {
    slug: "stainless-steel-shower-panel-gun-metal-grey",
    vertical: "bathroom-accessories",
    categorySlug: "showers",
    name: "304 Grade Stainless Steel Shower Panel with Head Shower, Hand Shower and Massage Jet",
    collection: "Shower Panel",
    shortDescription: "Stainless steel wall panel with overhead rain shower, hand shower and massage jet spray.",
    description:
      "A wall-mounted shower panel with a 304 grade stainless steel body, ABS shower and mixer components, and a PVC hose, finished in a matte gun metal grey that resists fingerprints and water stains. It combines a wide overhead rain shower, a handheld shower on a flexible hose, and a massage spray jet, with controls to switch between the three modes. The panel comes with a wall mounting hardware kit and user manual for installation, and is built for rust resistance in humid bathroom conditions.",
    finishes: ["Gun Metal Grey"],
    sizes: ["38 L x 15.5 W x 130 H cm"],
    specs: [
      { label: "Material", value: "304 Grade Stainless Steel body with ABS and PVC components" },
      { label: "Installation", value: "Wall-mounted with included hardware kit" },
      { label: "Functions", value: "Overhead rain shower, handheld shower, massage spray jet" },
      { label: "Finish", value: "Matte, fingerprint and water-stain resistant" },
      { label: "Weight", value: "5.14 kg" },
    ],
    tags: [],
    tone: "bath",
  },
  {
    slug: "solid-brass-3-in-1-shower-set-chrome",
    vertical: "bathroom-accessories",
    categorySlug: "showers",
    name: "Solid Brass 3 in 1 Shower Set with Overhead Shower and Dual-Function Handshower",
    collection: "Shower Panel",
    shortDescription: "Solid brass wall-mounted shower set with thermostatic overhead and dual-mode hand shower.",
    description:
      "A wall-mounted shower set built in solid brass with a nickel chrome mirror finish, pairing a thermostatic overhead shower head with a dual-function hand shower that offers both rainfall and waterfall outlets. An easy diverter control switches flow between the overhead and handheld shower, and an adjustable hot and cold knob manages water temperature. The set includes the shower head, a brass mounting bracket, a 1.5 meter hose, the temperature control knob, and fitting tape for wall installation.",
    finishes: ["Chrome"],
    sizes: [],
    specs: [
      { label: "Material", value: "Solid brass with nickel chrome mirror finish" },
      { label: "Valve Type", value: "Thermostatic with adjustable hot and cold knob" },
      { label: "Installation", value: "Wall-mounted" },
      { label: "Functions", value: "Overhead shower with rainfall and waterfall dual modes, handheld shower, diverter control" },
      { label: "Recommended Water Pressure", value: "2-3 bar" },
      { label: "Weight", value: "5.42 kg" },
    ],
    tags: [],
    tone: "bath",
  },

  // ---------- Faucets & Taps: Bathroom ----------
  {
    slug: "saga-single-lever-bib-tap",
    vertical: "bathroom-accessories",
    categorySlug: "faucets",
    name: "Single Lever Long Body Bib Tap with Water Saving Aerator (SAGA - Black)",
    collection: "Wall Mount Tap",
    shortDescription: "Single lever wall-mounted bib tap with brass spindle and water-saving aerator.",
    description:
      "A wall-mounted single lever bib tap built with a zinc body and a brass spindle for reliable, leak-free operation. It is fitted with an anti-drip mechanism and a water-saving aerator that regulates flow at the wash basin. The tap comes with a wall flange and Teflon tape for straightforward installation.",
    finishes: ["Black"],
    sizes: [],
    specs: [
      { label: "Body Material", value: "Zinc" },
      { label: "Spindle Type", value: "Brass Spindle" },
      { label: "Installation", value: "Wall Mount" },
      { label: "Flow/Aerator", value: "Water Saving Aerator" },
      { label: "Dimensions", value: "3 x 15 x 6 cm" },
    ],
    tags: [],
    tone: "bath",
  },
  {
    slug: "gold-brass-basin-mixer-tap",
    vertical: "bathroom-accessories",
    categorySlug: "faucets",
    name: "Wash Basin Mixer Tap - Pure Brass Hot and Cold Tap (Gold, 7881)",
    collection: "Wall Mount Tap",
    shortDescription: "Pure brass single-lever basin mixer with gold finish and pillar spout.",
    description:
      "A deck-mounted basin mixer tap made from pure brass with a gold finish, combining separate hot and cold water hoses through a single lever control. The pillar-style spout delivers a smooth, non-splashing stream through a built-in aerator, and the single-hole quick-connect design suits standard wash basins. It installs directly onto the basin deck for a compact, self-contained setup.",
    finishes: ["Gold"],
    sizes: [],
    specs: [
      { label: "Body Material", value: "Pure Brass" },
      { label: "Installation", value: "Deck Mount" },
      { label: "Flow/Aerator", value: "Water Saving Aerator" },
      { label: "Connection Type", value: "G1/2 Standard" },
      { label: "Dimensions", value: "30 x 19 x 4 cm" },
    ],
    tags: [],
    tone: "bath",
  },
  {
    slug: "two-way-quarter-turn-bib-cock",
    vertical: "bathroom-accessories",
    categorySlug: "faucets",
    name: "Two Way Tap for Washing Machine - Quarter Turn 2-in-1 Bib Cock (Black)",
    collection: "Wall Mount Tap",
    shortDescription: "Quarter-turn two-way bib cock for washing machine and basin connections.",
    description:
      "A wall-mounted two-way bib cock built from zinc with a brass spindle and ceramic cartridge for smooth quarter-turn operation. It provides two independent outlets, making it suitable for washing machine inlet connections alongside a wash basin or health faucet line. The tap ships with a wall flange, Teflon tape and a water-saving aerator, and is backed by a seven-year warranty against manufacturing defects.",
    finishes: ["Black"],
    sizes: [],
    specs: [
      { label: "Body Material", value: "Zinc with Brass Spindle" },
      { label: "Spindle Type", value: "Brass Spindle with Ceramic Cartridge" },
      { label: "Installation", value: "Wall Mount" },
      { label: "Mechanism", value: "Quarter Turn, 2-Way" },
      { label: "Warranty", value: "7 Years" },
    ],
    tags: [],
    tone: "bath",
  },
  {
    slug: "ico-909-basin-mixer-tap",
    vertical: "bathroom-accessories",
    categorySlug: "faucets",
    name: "Pure Brass Basin Mixer Tap Hot and Cold (ICO-909 - Chrome)",
    collection: "Mixer Tap",
    shortDescription: "Pure brass dual-handle basin mixer tap for wash basins, in chrome.",
    description:
      "A deck-mounted basin mixer tap made from pure brass with a chrome finish, using dual handles and a ceramic cartridge spindle to control hot and cold water independently. The leak-proof spindle is built for variable water conditions and needs only a wipe-down to maintain. It ships with Teflon tape for a straightforward wash basin installation, and is covered by a seven-year warranty against manufacturing defects.",
    finishes: ["Chrome"],
    sizes: [],
    specs: [
      { label: "Body Material", value: "Pure Brass" },
      { label: "Spindle Type", value: "Ceramic Cartridge" },
      { label: "Installation", value: "Deck Mount" },
      { label: "Warranty", value: "7 Years" },
    ],
    tags: [],
    tone: "bath",
  },

  // ---------- Faucets & Taps: Kitchen ----------
  {
    slug: "pac-1811-long-spout-sink-tap",
    vertical: "kitchen",
    categorySlug: "kitchen-faucets-sinks",
    name: "Pure Brass Sink Tap with 12 Inch Long Spout (PAC-1811 - Chrome)",
    collection: "Wall Mount Tap",
    shortDescription: "Pure brass wall-mounted kitchen tap with a 12-inch swiveling spout.",
    description:
      "A wall-mounted kitchen sink tap made from pure brass with a chrome finish, built around a smooth-turning ceramic cartridge for quarter-turn control. Its 12-inch spout swivels a full 360 degrees and ends in a water-saving nozzle that produces a gentle, splash-free stream. The tap comes with a brass wall flange and Teflon tape, and carries a seven-year warranty against manufacturing defects.",
    finishes: ["Chrome"],
    sizes: ["12 inch spout"],
    specs: [
      { label: "Body Material", value: "Pure Brass" },
      { label: "Spindle Type", value: "Ceramic Cartridge" },
      { label: "Installation", value: "Wall Mount" },
      { label: "Flow/Aerator", value: "Water Saving Nozzle" },
      { label: "Warranty", value: "7 Years" },
    ],
    tags: [],
    tone: "kitchen",
  },
  {
    slug: "single-lever-black-kitchen-tap",
    vertical: "kitchen",
    categorySlug: "kitchen-faucets-sinks",
    name: "Single Lever Kitchen Sink Tap with Water Saving Aerator (Black)",
    collection: "Sink Tap",
    shortDescription: "Single lever kitchen tap with brass spindle and black finish.",
    description:
      "A wall-mounted single lever kitchen sink tap with a zinc alloy body and a brass spindle for quarter-turn control. A ceramic cartridge and aerator work together to give a smooth, splash-free flow that copes well with hard water. It is finished in black and installs with the included wall flange and Teflon tape.",
    finishes: ["Black"],
    sizes: [],
    specs: [
      { label: "Body Material", value: "Zinc Alloy" },
      { label: "Spindle Type", value: "Brass Spindle" },
      { label: "Installation", value: "Wall Mount" },
      { label: "Flow/Aerator", value: "Water Saving Aerator" },
    ],
    tags: [],
    tone: "kitchen",
  },
  {
    slug: "pri-310-swivel-spout-sink-tap",
    vertical: "kitchen",
    categorySlug: "kitchen-faucets-sinks",
    name: "Kitchen Sink Tap with 360 Degree Swivel Spout (PRI-310 - Chrome)",
    collection: "Sink Tap",
    shortDescription: "Brass kitchen tap with a 360-degree swivel spout in chrome.",
    description:
      "A wall-mounted kitchen sink tap in brass with a chrome finish, fitted with a 360-degree swivel spout for flexible reach across the basin. A ceramic cartridge gives smooth quarter-turn control, while the water-saving nozzle and aerator keep the stream splash-free. It comes with a brass wall flange and Teflon tape, and is covered by a seven-year warranty.",
    finishes: ["Chrome"],
    sizes: [],
    specs: [
      { label: "Body Material", value: "Brass" },
      { label: "Spindle Type", value: "Ceramic Cartridge" },
      { label: "Installation", value: "Wall Mount" },
      { label: "Flow/Aerator", value: "Water Saving Nozzle" },
      { label: "Warranty", value: "7 Years" },
    ],
    tags: [],
    tone: "kitchen",
  },
  {
    slug: "saga-swivel-spout-sink-mixer",
    vertical: "kitchen",
    categorySlug: "kitchen-faucets-sinks",
    name: "Sink Mixer Tap with 360 Degree Swivel Spout (Saga - Black)",
    collection: "Mixer Tap",
    shortDescription: "Twin-handle sink mixer with 360-degree spout and black finish.",
    description:
      "A wall-mounted sink mixer tap with a zinc alloy body and a brass spindle, using twin handles to blend hot and cold water through a 360-degree swivel spout. A ceramic cartridge controls flow, and an aerator gives a smooth, splash-free stream suited to variable water conditions. It is finished in black and installs with the included wall flange and Teflon tape.",
    finishes: ["Black"],
    sizes: [],
    specs: [
      { label: "Body Material", value: "Zinc Alloy" },
      { label: "Spindle Type", value: "Brass Spindle with Ceramic Cartridge" },
      { label: "Installation", value: "Wall Mount" },
      { label: "Flow/Aerator", value: "Aerator" },
    ],
    tags: [],
    tone: "kitchen",
  },
  {
    slug: "lea-714-brass-sink-mixer",
    vertical: "kitchen",
    categorySlug: "kitchen-faucets-sinks",
    name: "Pure Brass Sink Mixer Tap Hot and Cold (LEA-714 - Chrome)",
    collection: "Mixer Tap",
    shortDescription: "Virgin brass twin-handle sink mixer with chrome finish for kitchens.",
    description:
      "A wall-mounted kitchen sink mixer tap built from virgin brass with a nickel-chrome finish, blending hot and cold water through a single spout via twin handles. A ceramic cartridge spindle and aerator deliver a smooth, foam-flow stream that resists splashing, and the removable aerator simplifies cleaning. It comes with a brass wall flange and Teflon tape, and is backed by a seven-year warranty.",
    finishes: ["Chrome"],
    sizes: [],
    specs: [
      { label: "Body Material", value: "Virgin Brass" },
      { label: "Spindle Type", value: "Ceramic Cartridge" },
      { label: "Installation", value: "Wall Mount" },
      { label: "Flow/Aerator", value: "Aerator" },
      { label: "Warranty", value: "7 Years" },
    ],
    tags: [],
    tone: "kitchen",
  },

  // ---------- Hardware: Door Hardware ----------
  {
    slug: "knot-mute-door-handle",
    vertical: "hardware",
    categorySlug: "door-hardware",
    name: "KNOT Minimalist Mute Door Handle",
    collection: "Door Hardware",
    shortDescription: "Minimalist mute door handle for quiet operation on internal privacy doors.",
    description:
      "A minimalist door handle designed for quiet, smooth operation on internal doors. It reduces latching noise by up to 40 percent and features an ergonomic grip suited to bathroom and privacy door applications. The handle is compatible with doors between 32 and 60 millimeters thick.",
    finishes: ["Brushed Brass", "Graphite Matt"],
    sizes: [],
    specs: [
      { label: "Application", value: "Internal doors, bathroom and privacy functions" },
      { label: "Door thickness compatibility", value: "32-60 mm" },
      { label: "Noise reduction", value: "Up to 40% reduction in latching noise" },
      { label: "Finish", value: "Brushed Brass or Graphite Matt" },
    ],
    tags: [],
    tone: "hardware",
  },
  {
    slug: "minimu-magnetic-door-handle",
    vertical: "hardware",
    categorySlug: "door-hardware",
    name: "MINIMU Minimalist Mute Door Handle",
    collection: "Door Hardware",
    shortDescription: "Concealed magnetic-lock door handle with a screwless body for quiet, seamless operation.",
    description:
      "A concealed door handle that combines a screwless lock body with a silent magnetic locking mechanism for quiet operation. CNC fine-engraved detailing gives the handle a clean, seamless appearance, and the mechanism reduces latching noise by up to 40 percent. It is designed for doors between 38 and 55 millimeters thick.",
    finishes: ["Graphite Matt", "Elegant Gold"],
    sizes: [],
    specs: [
      { label: "Lock/Cylinder type", value: "Silent magnetic lock" },
      { label: "Lock body", value: "Concealed, screwless" },
      { label: "Door thickness compatibility", value: "38-55 mm" },
      { label: "Design feature", value: "CNC fine-engraved" },
      { label: "Noise reduction", value: "Up to 40%" },
    ],
    tags: [],
    tone: "hardware",
  },
  {
    slug: "touch-plus-concealed-lockset",
    vertical: "hardware",
    categorySlug: "door-hardware",
    name: "Touch Plus Concealed Lockset",
    collection: "Door Hardware",
    shortDescription: "Concealed magnetic lockset with a knob for modern internal doors.",
    description:
      "A concealed lockset for modern interior doors that uses a magnetic locking mechanism for silent, secure operation. The design pairs a low-profile concealed lock body with a knob for convenient use. It is suited to internal doors between 38 and 60 millimeters thick.",
    finishes: ["PT", "GM", "SN"],
    sizes: [],
    specs: [
      { label: "Lock/Cylinder type", value: "Magnetic locking mechanism" },
      { label: "Lock body", value: "Concealed lockset" },
      { label: "Door thickness compatibility", value: "38-60 mm" },
      { label: "Application", value: "Internal doors" },
    ],
    tags: [],
    tone: "hardware",
  },

  // ---------- Hardware: Locks & Security ----------
  {
    slug: "lapo-heavy-duty-mortise-lock",
    vertical: "hardware",
    categorySlug: "locks-security",
    name: "Heavy-Duty Mortise Door Lock for Home Main Door & Bedroom with Handle |Strong 70mm Cylinder | 50x85mm Body | 3",
    collection: "Door Lock",
    shortDescription: "Heavy-duty mortise door lock for main doors and bedrooms; details pending manual review.",
    description:
      "Needs content — source page could not be fetched automatically, please review the link and add real description/specs manually.",
    finishes: [],
    sizes: [],
    specs: [
      { label: "Cylinder", value: "70 mm (per listing title)" },
      { label: "Body size", value: "50 x 85 mm (per listing title)" },
      { label: "Number of keys", value: "Not confirmed — needs manual review" },
    ],
    tags: [],
    tone: "hardware",
  },
  {
    slug: "godrej-mortise-lock-1ck-em01",
    vertical: "hardware",
    categorySlug: "locks-security",
    name: 'Godrej Mortise Lock I Handle Set 1CK EM01 I Antique Brass Finish I Pin Cylinder Technology I 3 Keys I Double Throw I 5" Handle I Left/Right Handed Door Operation I 1 Year Warranty',
    collection: "Door Lock",
    shortDescription: "Godrej mortise lock and handle set; specifications pending manual review from source page.",
    description:
      "Needs content — source page could not be fetched automatically, please review the link and add real description/specs manually.",
    finishes: ["Antique Brass"],
    sizes: ["5 inch handle"],
    specs: [
      { label: "Cylinder type", value: "Pin cylinder technology" },
      { label: "Number of keys", value: "3" },
      { label: "Locking type", value: "Double throw" },
      { label: "Warranty", value: "1 year" },
      { label: "Finish", value: "Antique Brass" },
    ],
    tags: [],
    tone: "hardware",
  },
  {
    slug: "plantex-main-door-mortise-lock",
    vertical: "hardware",
    categorySlug: "locks-security",
    name: "Main Door Mortise Lock and Heavy-Duty Door Knob Pull Handle Set (Brass Antique - Black)",
    collection: "Door Lock",
    shortDescription: "Heavy-duty brass mortise lock and knob handle set for home or office main doors.",
    description:
      "A heavy-duty mortise lock and knob handle set made from zinc alloy and brass, suited to main doors in homes and offices. The set includes a deadbolt operated by key on one side and a knob on the other, with reversible fitting for left- or right-handed doors. It is rated for over 300,000 operating cycles and finished in brass antique and black.",
    finishes: ["Brass Antique", "Black"],
    sizes: [],
    specs: [
      { label: "Material", value: "Zinc alloy and brass" },
      { label: "Cylinder", value: "70 mm" },
      { label: "Body size", value: "50 x 85 mm" },
      { label: "Door thickness compatibility", value: "25-50 mm" },
      { label: "Number of keys", value: "3" },
      { label: "Warranty", value: "36 months on handles and cylinder" },
    ],
    tags: [],
    tone: "hardware",
  },
  {
    slug: "duke-dyna-2-1-door-lock",
    vertical: "hardware",
    categorySlug: "locks-security",
    name: "DUKE Door Lock Dyna 2-1 Heavy Main Door Lock with One Solid Hudka and Latch 6 Levers 100mm Double Action Locking with 2 Chrome Finish Keys",
    collection: "Door Lock",
    shortDescription: "Duke Dyna 2-1 heavy-duty main door lock; specifications pending manual review from source page.",
    description:
      "Needs content — source page could not be fetched automatically, please review the link and add real description/specs manually.",
    finishes: [],
    sizes: ["100 mm"],
    specs: [
      { label: "Lever count", value: "6 levers" },
      { label: "Locking type", value: "Double action locking" },
      { label: "Number of keys", value: "2" },
      { label: "Key finish", value: "Chrome" },
    ],
    tags: [],
    tone: "hardware",
  },
];

export function getProductsByCategory(vertical: string, categorySlug: string) {
  return products.filter((p) => p.vertical === vertical && p.categorySlug === categorySlug);
}

export function getProductsByVertical(vertical: string) {
  return products.filter((p) => p.vertical === vertical);
}

export function getFeaturedProducts() {
  return products.filter((p) => p.featured);
}

export function getProduct(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function getRelatedProducts(product: Product, count = 4) {
  return products
    .filter((p) => p.slug !== product.slug && p.categorySlug === product.categorySlug)
    .slice(0, count);
}
